# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f635585fb5a49e329b3d63f6251aabaa3ced435b9d14a040abda0c7a0e6c5226a7b9a2d3c3218427debe104da798b0e814a863561a713e5220c9b209930b9bd

test:
  secret_key_base: 4b8cf201b80b76e39263b5f5b8551790b8b0d094e515f005f8c427c83e4d53b212b430aced7db2b7b11b09423d7933927c36bcd5a8d903421aad26a0e3304195

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
